name: sklearn-cancer-prediction
channels:
  - defaults
dependencies:
  - python=3.7.6
  - pip
  - pip:
    - mlflow==1.26.1
    - numpy==1.18.5
    - scikit-learn==0.23.1
    - scikit-plot==0.3.7
    - matplotlib==3.2.1
    - seaborn==0.10.1
    - git+https://github.com/oneconvergence/dkube.git@3.3.mp
    - protobuf==3.19.4
    - boto3  
