name: pytorch-example
channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - sklearn
  - cloudpickle==1.6.0
  - boto3
  - torchvision>=0.9.1
  - torch>=1.9.0
  - git+https://github.com/oneconvergence/dkube.git@3.3.mp
  - mlflow
